FROM node:14 AS frontend-build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm config set registry https://mirrors.cloud.tencent.com/npm/
RUN npm install
COPY frontend .
RUN npm run build

FROM nginx:alpine
COPY --from=frontend-build /app/dist /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/nginx.conf


EXPOSE 8080


CMD ["nginx", "-g", "daemon off;"]
