FROM node:20-alpine AS frontend-build
WORKDIR /app
# COPY frontend/package*.json ./
# COPY frontend/vue.config.js ./
# COPY frontend/.npmrc ./
COPY frontend .
ARG NPMRC_ENV=home
COPY .npmrc.${NPMRC_ENV} .npmrc
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=frontend-build /app/dist /usr/share/nginx/html
COPY config/nginx.conf /etc/nginx/nginx.conf


EXPOSE 8080


CMD ["nginx", "-g", "daemon off;"]
